### ISSUE TITLE
Incorrect `get_or_create` application for Rust client

### ISSUE THREAD

**Issue by ksindi** [svix/svix-docs#105]
Rust example in API docs shows:
```
let application_out = svix.application().get_or_create(ApplicationIn {
    uid: "unique-app-identifier".to_string(),
    name: "My first application".to_string(),
    rate_limit: 1000,
    metadata: None
}).await?;
```

Some of the values are options and there is a second param to the function. Correct example should be:
```
let application_out = svix
        .application()
        .get_or_create(
            ApplicationIn {
                uid: Some("unique-app-identifier".to_string()),
                name: "My first application".to_string(),
                rate_limit: Some(1000),
                metadata: None,
            },
            None,
        )
        .await;
```

**Comment by tasn** [comment]
Thanks for the report! Is this in https://api.svix.com/docs or in docs.svix.com?

**Comment by tasn** [comment]
Nevermind, found it: https://api.svix.com/docs#tag/Application/operation/create_application_api_v1_app__post

**Comment by ksindi** [comment]
I suspect most if not all of Rust client example codes have issues around params needing to be Option or wrong number of inputs to function.

**Comment by tasn** [comment]
Closing this ticket as there's a PR out with the fix (it's on a private repo).

**Comment by tasn** [comment]
Fix is out, sorry for the trouble, and let us know if you spot anything else.
We fixed the issue with `Some`, and the missing `None` when passed to `options`.
