### ISSUE TITLE
Remove box-shadow on logo

### ISSUE THREAD

**Issue by svix-frank** [svix/svix-docs#48]
There's a funky looking  box-shadow on the logo we should remove:
<img width="302" alt="Screen Shot 2021-09-23 at 2 11 28 PM" src="https://user-images.githubusercontent.com/84723448/134561514-423d29ab-eece-41db-abcf-fb973fb2cc4b.png">

**Comment by svix-liam** [comment]
Good catch! will fix shortly

**Comment by svix-frank** [comment]
fixed in https://github.com/svix/svix-docs/commit/188124ce11a177383ed42d00b346ef7186e44547
